---
server: irc.gamesurge.net
channels:
-   '#eebstest'
nick: joshbot
user: joshbot
realname: joshbot
plugins:
    plugins:
    -   Huggle
    -   Bucket
    -   TeamFuncom
    options:
        Bucket:
            minimum_trigger_length: 4
...
